name: n_plus_one
description: N + 1 mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  badges: ^2.0.2
  expandable: ^5.0.1

  # state-managment
  flutter_bloc: ^8.0.1

  # compare objects with Properties
  equatable: ^2.0.3

  # обработка ошибок
  dartz: ^0.10.1

  # проверка интернет-соединения
  internet_connection_checker: ^0.0.1+3

  # локальное хранилище данных
  shared_preferences: ^2.0.9

  # DI
  get_it: ^7.2.0

  # HTTP
  dio: ^4.0.4
  http: ^0.13.4 # deprecates

  # Google Sign In
  google_sign_in: ^5.2.1
  # firebase_core: ^1.10.6
  # firebase_auth: ^3.3.4

  # Countries
  country_list: ^0.0.5

  # Images
  image_picker: ^0.8.4+4

  # Code Generation
  openapi_generator_annotations: ^3.3.0
  nplone_api:
    path: .nplone_api_package

  # Text Formatter & Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Logging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter: ^1.15.0
  flutter_lints: ^1.0.4
  # dart_code_metrics: ^4.8.1
  
  # Code Generation
  openapi_generator: ^3.3.0+1
  build_runner: ^2.1.7
  build_resolvers: ^2.0.6
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/actions/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# Localization configuration
flutter_intl:
  main_locale: en_GB
  enabled: true
  class_name: S
  output_dir: lib\core\localization\generated
  arb_dir: lib\core\localization\l10n
